package lime;


import lime.utils.Assets;


class AssetData {

	private static var initialized:Bool = false;
	
	public static var library = new #if haxe3 Map <String, #else Hash <#end LibraryType> ();
	public static var path = new #if haxe3 Map <String, #else Hash <#end String> ();
	public static var type = new #if haxe3 Map <String, #else Hash <#end AssetType> ();	
	
	public static function initialize():Void {
		
		if (!initialized) {
			
			path.set ("assets/data/achievement.csv", "assets/data/achievement.csv");
			type.set ("assets/data/achievement.csv", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/deathtype.csv", "assets/data/deathtype.csv");
			type.set ("assets/data/deathtype.csv", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/hint.csv", "assets/data/hint.csv");
			type.set ("assets/data/hint.csv", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/message.csv", "assets/data/message.csv");
			type.set ("assets/data/message.csv", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/name/female.cpp", "assets/data/name/female.cpp");
			type.set ("assets/data/name/female.cpp", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/name/male.cpp", "assets/data/name/male.cpp");
			type.set ("assets/data/name/male.cpp", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/nameentry.csv", "assets/data/nameentry.csv");
			type.set ("assets/data/nameentry.csv", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/staffroll.csv", "assets/data/staffroll.csv");
			type.set ("assets/data/staffroll.csv", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/statistics.csv", "assets/data/statistics.csv");
			type.set ("assets/data/statistics.csv", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/stats.csv", "assets/data/stats.csv");
			type.set ("assets/data/stats.csv", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/title.csv", "assets/data/title.csv");
			type.set ("assets/data/title.csv", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/uitext.csv", "assets/data/uitext.csv");
			type.set ("assets/data/uitext.csv", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/events/001.tmx", "assets/events/001.tmx");
			type.set ("assets/events/001.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/events/002.tmx", "assets/events/002.tmx");
			type.set ("assets/events/002.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/events/003.tmx", "assets/events/003.tmx");
			type.set ("assets/events/003.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/events/010.tmx", "assets/events/010.tmx");
			type.set ("assets/events/010.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/events/cursor.png", "assets/events/cursor.png");
			type.set ("assets/events/cursor.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/events/ending.cpp", "assets/events/ending.cpp");
			type.set ("assets/events/ending.cpp", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/events/ending.png", "assets/events/ending.png");
			type.set ("assets/events/ending.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/events/matatabi.png", "assets/events/matatabi.png");
			type.set ("assets/events/matatabi.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/events/message.csv", "assets/events/message.csv");
			type.set ("assets/events/message.csv", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/events/opening.cpp", "assets/events/opening.cpp");
			type.set ("assets/events/opening.cpp", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/events/tileset1.png", "assets/events/tileset1.png");
			type.set ("assets/events/tileset1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/events/tileset10.png", "assets/events/tileset10.png");
			type.set ("assets/events/tileset10.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/events/tileset2.png", "assets/events/tileset2.png");
			type.set ("assets/events/tileset2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/events/tileset3.png", "assets/events/tileset3.png");
			type.set ("assets/events/tileset3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/events/tileset4.png", "assets/events/tileset4.png");
			type.set ("assets/events/tileset4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/events/tileset5.png", "assets/events/tileset5.png");
			type.set ("assets/events/tileset5.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/events/tileset6.png", "assets/events/tileset6.png");
			type.set ("assets/events/tileset6.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/events/tileset7.png", "assets/events/tileset7.png");
			type.set ("assets/events/tileset7.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/events/tileset8.png", "assets/events/tileset8.png");
			type.set ("assets/events/tileset8.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/events/tileset9.png", "assets/events/tileset9.png");
			type.set ("assets/events/tileset9.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/events/window.png", "assets/events/window.png");
			type.set ("assets/events/window.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/font/fangzhengxiangsu14.ttf", "assets/font/fangzhengxiangsu14.ttf");
			type.set ("assets/font/fangzhengxiangsu14.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("assets/font/font16x16.png", "assets/font/font16x16.png");
			type.set ("assets/font/font16x16.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/balloon.png", "assets/images/balloon.png");
			type.set ("assets/images/balloon.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/cat.png", "assets/images/cat.png");
			type.set ("assets/images/cat.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/cursor.png", "assets/images/cursor.png");
			type.set ("assets/images/cursor.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/door.png", "assets/images/door.png");
			type.set ("assets/images/door.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/effect.png", "assets/images/effect.png");
			type.set ("assets/images/effect.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/heart.png", "assets/images/heart.png");
			type.set ("assets/images/heart.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/item.png", "assets/images/item.png");
			type.set ("assets/images/item.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/kira.png", "assets/images/kira.png");
			type.set ("assets/images/kira.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/arachne.png", "assets/images/monster/arachne.png");
			type.set ("assets/images/monster/arachne.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/bat.png", "assets/images/monster/bat.png");
			type.set ("assets/images/monster/bat.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/bear.png", "assets/images/monster/bear.png");
			type.set ("assets/images/monster/bear.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/bee.png", "assets/images/monster/bee.png");
			type.set ("assets/images/monster/bee.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/beetle.png", "assets/images/monster/beetle.png");
			type.set ("assets/images/monster/beetle.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/bird.png", "assets/images/monster/bird.png");
			type.set ("assets/images/monster/bird.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/boar.png", "assets/images/monster/boar.png");
			type.set ("assets/images/monster/boar.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/bull.png", "assets/images/monster/bull.png");
			type.set ("assets/images/monster/bull.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/cat1.png", "assets/images/monster/cat1.png");
			type.set ("assets/images/monster/cat1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/cat2.png", "assets/images/monster/cat2.png");
			type.set ("assets/images/monster/cat2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/centipede.png", "assets/images/monster/centipede.png");
			type.set ("assets/images/monster/centipede.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/chicken.png", "assets/images/monster/chicken.png");
			type.set ("assets/images/monster/chicken.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/cockroach.png", "assets/images/monster/cockroach.png");
			type.set ("assets/images/monster/cockroach.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/cow.png", "assets/images/monster/cow.png");
			type.set ("assets/images/monster/cow.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/crab_ground.png", "assets/images/monster/crab_ground.png");
			type.set ("assets/images/monster/crab_ground.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/crab_water.png", "assets/images/monster/crab_water.png");
			type.set ("assets/images/monster/crab_water.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/crystal_golem.png", "assets/images/monster/crystal_golem.png");
			type.set ("assets/images/monster/crystal_golem.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/dark_elf1.png", "assets/images/monster/dark_elf1.png");
			type.set ("assets/images/monster/dark_elf1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/dark_elf2.png", "assets/images/monster/dark_elf2.png");
			type.set ("assets/images/monster/dark_elf2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/dark_elf3.png", "assets/images/monster/dark_elf3.png");
			type.set ("assets/images/monster/dark_elf3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/dark_elf4.png", "assets/images/monster/dark_elf4.png");
			type.set ("assets/images/monster/dark_elf4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/doe.png", "assets/images/monster/doe.png");
			type.set ("assets/images/monster/doe.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/dog1.png", "assets/images/monster/dog1.png");
			type.set ("assets/images/monster/dog1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/dog2.png", "assets/images/monster/dog2.png");
			type.set ("assets/images/monster/dog2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/dummy.png", "assets/images/monster/dummy.png");
			type.set ("assets/images/monster/dummy.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/earth_demon.png", "assets/images/monster/earth_demon.png");
			type.set ("assets/images/monster/earth_demon.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/eel_ground.png", "assets/images/monster/eel_ground.png");
			type.set ("assets/images/monster/eel_ground.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/eel_water.png", "assets/images/monster/eel_water.png");
			type.set ("assets/images/monster/eel_water.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/empusa.png", "assets/images/monster/empusa.png");
			type.set ("assets/images/monster/empusa.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/evil_eye.png", "assets/images/monster/evil_eye.png");
			type.set ("assets/images/monster/evil_eye.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/fairy.png", "assets/images/monster/fairy.png");
			type.set ("assets/images/monster/fairy.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/fire_demon.png", "assets/images/monster/fire_demon.png");
			type.set ("assets/images/monster/fire_demon.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/floating_skull.png", "assets/images/monster/floating_skull.png");
			type.set ("assets/images/monster/floating_skull.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/fly.png", "assets/images/monster/fly.png");
			type.set ("assets/images/monster/fly.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/frog.png", "assets/images/monster/frog.png");
			type.set ("assets/images/monster/frog.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/fungus.png", "assets/images/monster/fungus.png");
			type.set ("assets/images/monster/fungus.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/gargoyle_fly.png", "assets/images/monster/gargoyle_fly.png");
			type.set ("assets/images/monster/gargoyle_fly.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/gargoyle_walk.png", "assets/images/monster/gargoyle_walk.png");
			type.set ("assets/images/monster/gargoyle_walk.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/gas_spore.png", "assets/images/monster/gas_spore.png");
			type.set ("assets/images/monster/gas_spore.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/gelatinous_cube.png", "assets/images/monster/gelatinous_cube.png");
			type.set ("assets/images/monster/gelatinous_cube.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/ghost.png", "assets/images/monster/ghost.png");
			type.set ("assets/images/monster/ghost.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/ghoul.png", "assets/images/monster/ghoul.png");
			type.set ("assets/images/monster/ghoul.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/gillman_ground.png", "assets/images/monster/gillman_ground.png");
			type.set ("assets/images/monster/gillman_ground.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/gillman_water.png", "assets/images/monster/gillman_water.png");
			type.set ("assets/images/monster/gillman_water.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/gnole1.png", "assets/images/monster/gnole1.png");
			type.set ("assets/images/monster/gnole1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/gnole2.png", "assets/images/monster/gnole2.png");
			type.set ("assets/images/monster/gnole2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/goat.png", "assets/images/monster/goat.png");
			type.set ("assets/images/monster/goat.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/goatman1.png", "assets/images/monster/goatman1.png");
			type.set ("assets/images/monster/goatman1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/goatman2.png", "assets/images/monster/goatman2.png");
			type.set ("assets/images/monster/goatman2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/goblin1.png", "assets/images/monster/goblin1.png");
			type.set ("assets/images/monster/goblin1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/goblin2.png", "assets/images/monster/goblin2.png");
			type.set ("assets/images/monster/goblin2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/goblin3.png", "assets/images/monster/goblin3.png");
			type.set ("assets/images/monster/goblin3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/goblin4.png", "assets/images/monster/goblin4.png");
			type.set ("assets/images/monster/goblin4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/golem.png", "assets/images/monster/golem.png");
			type.set ("assets/images/monster/golem.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/gorilla.png", "assets/images/monster/gorilla.png");
			type.set ("assets/images/monster/gorilla.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/grizzy_bear.png", "assets/images/monster/grizzy_bear.png");
			type.set ("assets/images/monster/grizzy_bear.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/hairy_demon.png", "assets/images/monster/hairy_demon.png");
			type.set ("assets/images/monster/hairy_demon.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/harpy_fly.png", "assets/images/monster/harpy_fly.png");
			type.set ("assets/images/monster/harpy_fly.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/harpy_walk.png", "assets/images/monster/harpy_walk.png");
			type.set ("assets/images/monster/harpy_walk.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/homunculus.png", "assets/images/monster/homunculus.png");
			type.set ("assets/images/monster/homunculus.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/horse1.png", "assets/images/monster/horse1.png");
			type.set ("assets/images/monster/horse1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/horse2.png", "assets/images/monster/horse2.png");
			type.set ("assets/images/monster/horse2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/horse3.png", "assets/images/monster/horse3.png");
			type.set ("assets/images/monster/horse3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/horse4.png", "assets/images/monster/horse4.png");
			type.set ("assets/images/monster/horse4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/ice_demon.png", "assets/images/monster/ice_demon.png");
			type.set ("assets/images/monster/ice_demon.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/imp.png", "assets/images/monster/imp.png");
			type.set ("assets/images/monster/imp.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/insect_demon.png", "assets/images/monster/insect_demon.png");
			type.set ("assets/images/monster/insect_demon.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/insectivorous_plant.png", "assets/images/monster/insectivorous_plant.png");
			type.set ("assets/images/monster/insectivorous_plant.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/invader.png", "assets/images/monster/invader.png");
			type.set ("assets/images/monster/invader.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/iron_golem.png", "assets/images/monster/iron_golem.png");
			type.set ("assets/images/monster/iron_golem.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/jelly.png", "assets/images/monster/jelly.png");
			type.set ("assets/images/monster/jelly.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/jellyfish.png", "assets/images/monster/jellyfish.png");
			type.set ("assets/images/monster/jellyfish.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/legion.png", "assets/images/monster/legion.png");
			type.set ("assets/images/monster/legion.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/lesser_fiend1.png", "assets/images/monster/lesser_fiend1.png");
			type.set ("assets/images/monster/lesser_fiend1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/lesser_fiend2.png", "assets/images/monster/lesser_fiend2.png");
			type.set ("assets/images/monster/lesser_fiend2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/liche.png", "assets/images/monster/liche.png");
			type.set ("assets/images/monster/liche.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/lizard.png", "assets/images/monster/lizard.png");
			type.set ("assets/images/monster/lizard.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/lizardman1.png", "assets/images/monster/lizardman1.png");
			type.set ("assets/images/monster/lizardman1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/lizardman2.png", "assets/images/monster/lizardman2.png");
			type.set ("assets/images/monster/lizardman2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/magot.png", "assets/images/monster/magot.png");
			type.set ("assets/images/monster/magot.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/mandragora.png", "assets/images/monster/mandragora.png");
			type.set ("assets/images/monster/mandragora.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/mantis.png", "assets/images/monster/mantis.png");
			type.set ("assets/images/monster/mantis.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/medousa.png", "assets/images/monster/medousa.png");
			type.set ("assets/images/monster/medousa.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/mindflayer.png", "assets/images/monster/mindflayer.png");
			type.set ("assets/images/monster/mindflayer.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/minotaur1.png", "assets/images/monster/minotaur1.png");
			type.set ("assets/images/monster/minotaur1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/minotaur2.png", "assets/images/monster/minotaur2.png");
			type.set ("assets/images/monster/minotaur2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/mosquito.png", "assets/images/monster/mosquito.png");
			type.set ("assets/images/monster/mosquito.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/mummy.png", "assets/images/monster/mummy.png");
			type.set ("assets/images/monster/mummy.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/myconid.png", "assets/images/monster/myconid.png");
			type.set ("assets/images/monster/myconid.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/nightmare.png", "assets/images/monster/nightmare.png");
			type.set ("assets/images/monster/nightmare.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/octopus_ground.png", "assets/images/monster/octopus_ground.png");
			type.set ("assets/images/monster/octopus_ground.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/octopus_water.png", "assets/images/monster/octopus_water.png");
			type.set ("assets/images/monster/octopus_water.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/ogre1.png", "assets/images/monster/ogre1.png");
			type.set ("assets/images/monster/ogre1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/ogre2.png", "assets/images/monster/ogre2.png");
			type.set ("assets/images/monster/ogre2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/orc1.png", "assets/images/monster/orc1.png");
			type.set ("assets/images/monster/orc1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/orc2.png", "assets/images/monster/orc2.png");
			type.set ("assets/images/monster/orc2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/panther.png", "assets/images/monster/panther.png");
			type.set ("assets/images/monster/panther.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/pig.png", "assets/images/monster/pig.png");
			type.set ("assets/images/monster/pig.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/pillbug.png", "assets/images/monster/pillbug.png");
			type.set ("assets/images/monster/pillbug.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/poison_demon.png", "assets/images/monster/poison_demon.png");
			type.set ("assets/images/monster/poison_demon.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/polar_bear.png", "assets/images/monster/polar_bear.png");
			type.set ("assets/images/monster/polar_bear.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/pumpkin_head.png", "assets/images/monster/pumpkin_head.png");
			type.set ("assets/images/monster/pumpkin_head.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/rat.png", "assets/images/monster/rat.png");
			type.set ("assets/images/monster/rat.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/ratman1.png", "assets/images/monster/ratman1.png");
			type.set ("assets/images/monster/ratman1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/ratman2.png", "assets/images/monster/ratman2.png");
			type.set ("assets/images/monster/ratman2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/reaper.png", "assets/images/monster/reaper.png");
			type.set ("assets/images/monster/reaper.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/saber_tiger.png", "assets/images/monster/saber_tiger.png");
			type.set ("assets/images/monster/saber_tiger.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/scorpion.png", "assets/images/monster/scorpion.png");
			type.set ("assets/images/monster/scorpion.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/sea_serpent.png", "assets/images/monster/sea_serpent.png");
			type.set ("assets/images/monster/sea_serpent.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/shadow_demon.png", "assets/images/monster/shadow_demon.png");
			type.set ("assets/images/monster/shadow_demon.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/sheep.png", "assets/images/monster/sheep.png");
			type.set ("assets/images/monster/sheep.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/shellfish.png", "assets/images/monster/shellfish.png");
			type.set ("assets/images/monster/shellfish.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/shrieker.png", "assets/images/monster/shrieker.png");
			type.set ("assets/images/monster/shrieker.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/skeleton1.png", "assets/images/monster/skeleton1.png");
			type.set ("assets/images/monster/skeleton1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/skeleton2.png", "assets/images/monster/skeleton2.png");
			type.set ("assets/images/monster/skeleton2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/skeleton3.png", "assets/images/monster/skeleton3.png");
			type.set ("assets/images/monster/skeleton3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/skeleton_dog.png", "assets/images/monster/skeleton_dog.png");
			type.set ("assets/images/monster/skeleton_dog.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/skeleton_horse.png", "assets/images/monster/skeleton_horse.png");
			type.set ("assets/images/monster/skeleton_horse.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/slime.png", "assets/images/monster/slime.png");
			type.set ("assets/images/monster/slime.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/slug.png", "assets/images/monster/slug.png");
			type.set ("assets/images/monster/slug.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/snail.png", "assets/images/monster/snail.png");
			type.set ("assets/images/monster/snail.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/snake.png", "assets/images/monster/snake.png");
			type.set ("assets/images/monster/snake.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/snake_man.png", "assets/images/monster/snake_man.png");
			type.set ("assets/images/monster/snake_man.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/snow_panther.png", "assets/images/monster/snow_panther.png");
			type.set ("assets/images/monster/snow_panther.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/snow_wolf.png", "assets/images/monster/snow_wolf.png");
			type.set ("assets/images/monster/snow_wolf.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/soldier_ant.png", "assets/images/monster/soldier_ant.png");
			type.set ("assets/images/monster/soldier_ant.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/specter.png", "assets/images/monster/specter.png");
			type.set ("assets/images/monster/specter.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/spider.png", "assets/images/monster/spider.png");
			type.set ("assets/images/monster/spider.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/stag.png", "assets/images/monster/stag.png");
			type.set ("assets/images/monster/stag.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/succubus.png", "assets/images/monster/succubus.png");
			type.set ("assets/images/monster/succubus.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/tentacle.png", "assets/images/monster/tentacle.png");
			type.set ("assets/images/monster/tentacle.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/tick.png", "assets/images/monster/tick.png");
			type.set ("assets/images/monster/tick.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/tiger.png", "assets/images/monster/tiger.png");
			type.set ("assets/images/monster/tiger.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/toad.png", "assets/images/monster/toad.png");
			type.set ("assets/images/monster/toad.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/vampire.png", "assets/images/monster/vampire.png");
			type.set ("assets/images/monster/vampire.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/vine.png", "assets/images/monster/vine.png");
			type.set ("assets/images/monster/vine.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/vulture_demon.png", "assets/images/monster/vulture_demon.png");
			type.set ("assets/images/monster/vulture_demon.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/water_demon.png", "assets/images/monster/water_demon.png");
			type.set ("assets/images/monster/water_demon.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/werewolf.png", "assets/images/monster/werewolf.png");
			type.set ("assets/images/monster/werewolf.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/wight.png", "assets/images/monster/wight.png");
			type.set ("assets/images/monster/wight.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/wind_demon.png", "assets/images/monster/wind_demon.png");
			type.set ("assets/images/monster/wind_demon.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/wolf.png", "assets/images/monster/wolf.png");
			type.set ("assets/images/monster/wolf.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/worker_ant.png", "assets/images/monster/worker_ant.png");
			type.set ("assets/images/monster/worker_ant.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/worm.png", "assets/images/monster/worm.png");
			type.set ("assets/images/monster/worm.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/wraith.png", "assets/images/monster/wraith.png");
			type.set ("assets/images/monster/wraith.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/wyvern.png", "assets/images/monster/wyvern.png");
			type.set ("assets/images/monster/wyvern.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/yeti.png", "assets/images/monster/yeti.png");
			type.set ("assets/images/monster/yeti.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/monster/zombie.png", "assets/images/monster/zombie.png");
			type.set ("assets/images/monster/zombie.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pad/a.png", "assets/images/pad/a.png");
			type.set ("assets/images/pad/a.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pad/b.png", "assets/images/pad/b.png");
			type.set ("assets/images/pad/b.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pad/background.png", "assets/images/pad/background.png");
			type.set ("assets/images/pad/background.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pad/down.png", "assets/images/pad/down.png");
			type.set ("assets/images/pad/down.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pad/left.png", "assets/images/pad/left.png");
			type.set ("assets/images/pad/left.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pad/right.png", "assets/images/pad/right.png");
			type.set ("assets/images/pad/right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pad/up.png", "assets/images/pad/up.png");
			type.set ("assets/images/pad/up.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/player.png", "assets/images/player.png");
			type.set ("assets/images/player.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/result/girl.png", "assets/images/result/girl.png");
			type.set ("assets/images/result/girl.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/result/girl2.png", "assets/images/result/girl2.png");
			type.set ("assets/images/result/girl2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/result/girl3.png", "assets/images/result/girl3.png");
			type.set ("assets/images/result/girl3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/result/kira.png", "assets/images/result/kira.png");
			type.set ("assets/images/result/kira.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/smoke.png", "assets/images/smoke.png");
			type.set ("assets/images/smoke.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/spike.png", "assets/images/spike.png");
			type.set ("assets/images/spike.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/tiles.png", "assets/images/tiles.png");
			type.set ("assets/images/tiles.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/title/bg.png", "assets/images/title/bg.png");
			type.set ("assets/images/title/bg.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/title/cloud1.png", "assets/images/title/cloud1.png");
			type.set ("assets/images/title/cloud1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/title/cloud2.png", "assets/images/title/cloud2.png");
			type.set ("assets/images/title/cloud2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/title/cloud3.png", "assets/images/title/cloud3.png");
			type.set ("assets/images/title/cloud3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/title/cloud4.png", "assets/images/title/cloud4.png");
			type.set ("assets/images/title/cloud4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/title/sunbeam.png", "assets/images/title/sunbeam.png");
			type.set ("assets/images/title/sunbeam.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ui/arrow.png", "assets/images/ui/arrow.png");
			type.set ("assets/images/ui/arrow.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ui/category/armor.png", "assets/images/ui/category/armor.png");
			type.set ("assets/images/ui/category/armor.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ui/category/food.png", "assets/images/ui/category/food.png");
			type.set ("assets/images/ui/category/food.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ui/category/orb.png", "assets/images/ui/category/orb.png");
			type.set ("assets/images/ui/category/orb.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ui/category/potion.png", "assets/images/ui/category/potion.png");
			type.set ("assets/images/ui/category/potion.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ui/category/ring.png", "assets/images/ui/category/ring.png");
			type.set ("assets/images/ui/category/ring.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ui/category/scroll.png", "assets/images/ui/category/scroll.png");
			type.set ("assets/images/ui/category/scroll.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ui/category/wand.png", "assets/images/ui/category/wand.png");
			type.set ("assets/images/ui/category/wand.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ui/category/weapon.png", "assets/images/ui/category/weapon.png");
			type.set ("assets/images/ui/category/weapon.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ui/enemylog_cursor.png", "assets/images/ui/enemylog_cursor.png");
			type.set ("assets/images/ui/enemylog_cursor.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ui/frame32x256.png", "assets/images/ui/frame32x256.png");
			type.set ("assets/images/ui/frame32x256.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ui/itemcommand.png", "assets/images/ui/itemcommand.png");
			type.set ("assets/images/ui/itemcommand.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ui/itemlog_cursor.png", "assets/images/ui/itemlog_cursor.png");
			type.set ("assets/images/ui/itemlog_cursor.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ui/listitem.png", "assets/images/ui/listitem.png");
			type.set ("assets/images/ui/listitem.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ui/listitem2.png", "assets/images/ui/listitem2.png");
			type.set ("assets/images/ui/listitem2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ui/message.png", "assets/images/ui/message.png");
			type.set ("assets/images/ui/message.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ui/messagetext.png", "assets/images/ui/messagetext.png");
			type.set ("assets/images/ui/messagetext.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ui/window200x100.png", "assets/images/ui/window200x100.png");
			type.set ("assets/images/ui/window200x100.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ui/window624x74.png", "assets/images/ui/window624x74.png");
			type.set ("assets/images/ui/window624x74.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/levels/000.tmx", "assets/levels/000.tmx");
			type.set ("assets/levels/000.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/001.tmx", "assets/levels/001.tmx");
			type.set ("assets/levels/001.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/002.tmx", "assets/levels/002.tmx");
			type.set ("assets/levels/002.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/003.tmx", "assets/levels/003.tmx");
			type.set ("assets/levels/003.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/004.tmx", "assets/levels/004.tmx");
			type.set ("assets/levels/004.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/005.tmx", "assets/levels/005.tmx");
			type.set ("assets/levels/005.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/006.tmx", "assets/levels/006.tmx");
			type.set ("assets/levels/006.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/007.tmx", "assets/levels/007.tmx");
			type.set ("assets/levels/007.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/008.tmx", "assets/levels/008.tmx");
			type.set ("assets/levels/008.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/009.tmx", "assets/levels/009.tmx");
			type.set ("assets/levels/009.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/010.tmx", "assets/levels/010.tmx");
			type.set ("assets/levels/010.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/011.tmx", "assets/levels/011.tmx");
			type.set ("assets/levels/011.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/012.tmx", "assets/levels/012.tmx");
			type.set ("assets/levels/012.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/013.tmx", "assets/levels/013.tmx");
			type.set ("assets/levels/013.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/014.tmx", "assets/levels/014.tmx");
			type.set ("assets/levels/014.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/015.tmx", "assets/levels/015.tmx");
			type.set ("assets/levels/015.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/016.tmx", "assets/levels/016.tmx");
			type.set ("assets/levels/016.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/017.tmx", "assets/levels/017.tmx");
			type.set ("assets/levels/017.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/018.tmx", "assets/levels/018.tmx");
			type.set ("assets/levels/018.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/019.tmx", "assets/levels/019.tmx");
			type.set ("assets/levels/019.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/020.tmx", "assets/levels/020.tmx");
			type.set ("assets/levels/020.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/021.tmx", "assets/levels/021.tmx");
			type.set ("assets/levels/021.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/022.tmx", "assets/levels/022.tmx");
			type.set ("assets/levels/022.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/023.tmx", "assets/levels/023.tmx");
			type.set ("assets/levels/023.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/024.tmx", "assets/levels/024.tmx");
			type.set ("assets/levels/024.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/025.tmx", "assets/levels/025.tmx");
			type.set ("assets/levels/025.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/026.tmx", "assets/levels/026.tmx");
			type.set ("assets/levels/026.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/027.tmx", "assets/levels/027.tmx");
			type.set ("assets/levels/027.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/028.tmx", "assets/levels/028.tmx");
			type.set ("assets/levels/028.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/029.tmx", "assets/levels/029.tmx");
			type.set ("assets/levels/029.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/030.tmx", "assets/levels/030.tmx");
			type.set ("assets/levels/030.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/031.tmx", "assets/levels/031.tmx");
			type.set ("assets/levels/031.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/032.tmx", "assets/levels/032.tmx");
			type.set ("assets/levels/032.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/033.tmx", "assets/levels/033.tmx");
			type.set ("assets/levels/033.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/034.tmx", "assets/levels/034.tmx");
			type.set ("assets/levels/034.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/035.tmx", "assets/levels/035.tmx");
			type.set ("assets/levels/035.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/036.tmx", "assets/levels/036.tmx");
			type.set ("assets/levels/036.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/037.tmx", "assets/levels/037.tmx");
			type.set ("assets/levels/037.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/038.tmx", "assets/levels/038.tmx");
			type.set ("assets/levels/038.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/039.tmx", "assets/levels/039.tmx");
			type.set ("assets/levels/039.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/040.tmx", "assets/levels/040.tmx");
			type.set ("assets/levels/040.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/041.tmx", "assets/levels/041.tmx");
			type.set ("assets/levels/041.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/042.tmx", "assets/levels/042.tmx");
			type.set ("assets/levels/042.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/043.tmx", "assets/levels/043.tmx");
			type.set ("assets/levels/043.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/044.tmx", "assets/levels/044.tmx");
			type.set ("assets/levels/044.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/045.tmx", "assets/levels/045.tmx");
			type.set ("assets/levels/045.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/046.tmx", "assets/levels/046.tmx");
			type.set ("assets/levels/046.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/047.tmx", "assets/levels/047.tmx");
			type.set ("assets/levels/047.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/048.tmx", "assets/levels/048.tmx");
			type.set ("assets/levels/048.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/049.tmx", "assets/levels/049.tmx");
			type.set ("assets/levels/049.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/050.tmx", "assets/levels/050.tmx");
			type.set ("assets/levels/050.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/500.tmx", "assets/levels/500.tmx");
			type.set ("assets/levels/500.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/enemy.csv", "assets/levels/enemy.csv");
			type.set ("assets/levels/enemy.csv", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/enemy_appear.csv", "assets/levels/enemy_appear.csv");
			type.set ("assets/levels/enemy_appear.csv", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/enemy_nightmare.csv", "assets/levels/enemy_nightmare.csv");
			type.set ("assets/levels/enemy_nightmare.csv", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/item_appear.csv", "assets/levels/item_appear.csv");
			type.set ("assets/levels/item_appear.csv", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/item_consumable.csv", "assets/levels/item_consumable.csv");
			type.set ("assets/levels/item_consumable.csv", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/item_equipment.csv", "assets/levels/item_equipment.csv");
			type.set ("assets/levels/item_equipment.csv", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/player.csv", "assets/levels/player.csv");
			type.set ("assets/levels/player.csv", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/levels/tilenone.png", "assets/levels/tilenone.png");
			type.set ("assets/levels/tilenone.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/levels/tileset.png", "assets/levels/tileset.png");
			type.set ("assets/levels/tileset.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("001", "assets/music/001.ogg");
			type.set ("001", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("002", "assets/music/002.ogg");
			type.set ("002", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("003", "assets/music/003.ogg");
			type.set ("003", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("004", "assets/music/004.ogg");
			type.set ("004", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("005", "assets/music/005.ogg");
			type.set ("005", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("006", "assets/music/006.ogg");
			type.set ("006", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("007", "assets/music/007.ogg");
			type.set ("007", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("008", "assets/music/008.ogg");
			type.set ("008", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("009", "assets/music/009.ogg");
			type.set ("009", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("010", "assets/music/010.ogg");
			type.set ("010", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("011", "assets/music/011.ogg");
			type.set ("011", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("012", "assets/music/012.ogg");
			type.set ("012", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("013", "assets/music/013.ogg");
			type.set ("013", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("014", "assets/music/014.ogg");
			type.set ("014", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("015", "assets/music/015.ogg");
			type.set ("015", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("016", "assets/music/016.ogg");
			type.set ("016", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("nightmare", "assets/music/nightmare.ogg");
			type.set ("nightmare", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("result", "assets/music/result.ogg");
			type.set ("result", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("op1", "assets/music/op1.ogg");
			type.set ("op1", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("op2", "assets/music/op2.ogg");
			type.set ("op2", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("pickup", "assets/sounds/pickup2.ogg");
			type.set ("pickup", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("foot", "assets/sounds/foot2.ogg");
			type.set ("foot", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("destroy", "assets/sounds/destroy.ogg");
			type.set ("destroy", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("hit", "assets/sounds/hit.ogg");
			type.set ("hit", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("critical", "assets/sounds/hit4.ogg");
			type.set ("critical", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("eat", "assets/sounds/eat.ogg");
			type.set ("eat", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("enemy", "assets/sounds/enemy.ogg");
			type.set ("enemy", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("equip", "assets/sounds/equip.ogg");
			type.set ("equip", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("put", "assets/sounds/put.ogg");
			type.set ("put", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("avoid", "assets/sounds/avoid2.ogg");
			type.set ("avoid", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("recover", "assets/sounds/recover.ogg");
			type.set ("recover", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("gameover", "assets/sounds/destroy2.ogg");
			type.set ("gameover", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("menu", "assets/sounds/menu.ogg");
			type.set ("menu", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("pi", "assets/sounds/pi.ogg");
			type.set ("pi", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("hint", "assets/sounds/hint.ogg");
			type.set ("hint", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("coin", "assets/sounds/coin.ogg");
			type.set ("coin", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("levelup", "assets/sounds/levelup.ogg");
			type.set ("levelup", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("badstatus", "assets/sounds/badstatus.ogg");
			type.set ("badstatus", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("warp", "assets/sounds/warp.ogg");
			type.set ("warp", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("error", "assets/sounds/error.ogg");
			type.set ("error", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("flash", "assets/sounds/flash.ogg");
			type.set ("flash", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("break", "assets/sounds/break.ogg");
			type.set ("break", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("roar", "assets/sounds/roar.ogg");
			type.set ("roar", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("powerup", "assets/sounds/powerup.ogg");
			type.set ("powerup", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("chime", "assets/sounds/chime.ogg");
			type.set ("chime", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("unlock", "assets/sounds/unlock.ogg");
			type.set ("unlock", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("flixel/sounds/beep.ogg", "flixel/sounds/beep.ogg");
			type.set ("flixel/sounds/beep.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("flixel/sounds/flixel.ogg", "flixel/sounds/flixel.ogg");
			type.set ("flixel/sounds/flixel.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("flixel/fonts/nokiafc22.ttf", "flixel/fonts/nokiafc22.ttf");
			type.set ("flixel/fonts/nokiafc22.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("flixel/fonts/monsterrat.ttf", "flixel/fonts/monsterrat.ttf");
			type.set ("flixel/fonts/monsterrat.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("flixel/images/ui/button.png", "flixel/images/ui/button.png");
			type.set ("flixel/images/ui/button.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/images/logo/default.png", "flixel/images/logo/default.png");
			type.set ("flixel/images/logo/default.png", Reflect.field (AssetType, "image".toUpperCase ()));
			
			
			initialized = true;
			
		} //!initialized
		
	} //initialize
	
	
} //AssetData
